"""Positive detection corpus. Each case: (id, filename, source, expected [(rule_id, algorithm, operation, key_size)]).
Compared as an exact multiset against the executable (non-comment) findings, so extras fail too."""

JH = "import java.security.*;\nimport javax.crypto.*;\n"
PYC = "cryptography.hazmat.primitives"
PY = [
    ("rsa_alias", "t.py", f"from {PYC}.asymmetric import rsa as r\nk = r.generate_private_key(65537, 3072)\n",
     [("PY-CRYPTOGRAPHY-RSA-001", "RSA", "key_generation", 3072)]),
    ("rsa_kw", "t.py", f"import {PYC}.asymmetric.rsa as rsa\nk = rsa.generate_private_key(key_size=4096, public_exponent=65537)\n",
     [("PY-CRYPTOGRAPHY-RSA-001", "RSA", "key_generation", 4096)]),
    ("rsa_fully_qualified", "t.py", f"import cryptography\nk = cryptography.hazmat.primitives.asymmetric.rsa.generate_private_key(65537, 2048)\n",
     [("PY-CRYPTOGRAPHY-RSA-001", "RSA", "key_generation", 2048)]),
    ("oaep_encrypt_decrypt", "t.py", f"from {PYC}.asymmetric import padding\nct = pub.encrypt(m, padding.OAEP(mgf=None, algorithm=None, label=None))\npt = priv.decrypt(ct, padding.OAEP(mgf=None, algorithm=None, label=None))\n",
     [("PY-CRYPTOGRAPHY-RSA-002", "RSA", "encryption", None), ("PY-CRYPTOGRAPHY-RSA-002", "RSA", "decryption", None)]),
    ("pss_pkcs1_sign_verify", "t.py", f"from {PYC}.asymmetric import padding\ns = key.sign(d, padding.PSS(mgf=None, salt_length=32), None)\npub.verify(s, d, padding.PKCS1v15(), None)\n",
     [("PY-CRYPTOGRAPHY-RSA-002", "RSA", "signature", None), ("PY-CRYPTOGRAPHY-RSA-002", "RSA", "verification", None)]),
    ("pycryptodome_rsa", "t.py", "from Crypto.PublicKey import RSA\nkey = RSA.generate(2048)\n",
     [("PY-PYCRYPTODOME-RSA-001", "RSA", "key_generation", 2048)]),
    ("pycryptodome_rsa_objects", "t.py", "from Crypto.Cipher import PKCS1_OAEP\nfrom Cryptodome.Signature import pkcs1_15\nc = PKCS1_OAEP.new(key)\ns = pkcs1_15.new(key)\n",
     [("PY-PYCRYPTODOME-RSA-002", "RSA", "encryption", None), ("PY-PYCRYPTODOME-RSA-002", "RSA", "signature", None)]),
    ("python_rsa_pkg", "t.py", "import rsa\npub, priv = rsa.newkeys(2048)\nc = rsa.encrypt(b'm', pub)\n",
     [("PY-RSA-RSA-001", "RSA", "key_generation", 2048), ("PY-RSA-RSA-001", "RSA", "encryption", None)]),
    ("dsa", "t.py", f"from {PYC}.asymmetric import dsa\nk = dsa.generate_private_key(2048)\n", [("PY-CRYPTOGRAPHY-DSA-001", "DSA", "key_generation", 2048)]),
    ("dh", "t.py", f"from {PYC}.asymmetric import dh\np = dh.generate_parameters(generator=2, key_size=2048)\n", [("PY-CRYPTOGRAPHY-DH-001", "DH", "key_generation", 2048)]),
    ("ecdsa_sign_verify", "t.py", f"from {PYC}.asymmetric import ec\ns = key.sign(d, ec.ECDSA(None))\npub.verify(s, d, ec.ECDSA(None))\n",
     [("PY-CRYPTOGRAPHY-ECDSA-001", "ECDSA", "signature", None), ("PY-CRYPTOGRAPHY-ECDSA-001", "ECDSA", "verification", None)]),
    ("ecdh", "t.py", f"from {PYC}.asymmetric import ec\nshared = key.exchange(ec.ECDH(), peer)\n", [("PY-CRYPTOGRAPHY-ECDH-001", "ECDH", "key_agreement", None)]),
    ("x25519", "t.py", f"from {PYC}.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey\nk = X25519PrivateKey.generate()\np = X25519PublicKey.from_public_bytes(b)\n",
     [("PY-CRYPTOGRAPHY-ECDH-001", "ECDH", "key_generation", None), ("PY-CRYPTOGRAPHY-ECDH-001", "ECDH", "key_agreement", None)]),
    ("ec_unresolved", "t.py", f"from {PYC}.asymmetric import ec\nk = ec.generate_private_key(ec.SECP256R1())\n", [("PY-CRYPTOGRAPHY-EC-001", "EC", "key_generation", None)]),
    ("ec_resolved_to_ecdsa", "t.py", f"from {PYC}.asymmetric import ec\nk = ec.generate_private_key(ec.SECP256R1())\ns = k.sign(d, ec.ECDSA(None))\n",
     [("PY-CRYPTOGRAPHY-EC-001", "ECDSA", "key_generation", None), ("PY-CRYPTOGRAPHY-ECDSA-001", "ECDSA", "signature", None)]),
    ("ec_resolved_to_ecdh", "t.py", f"from {PYC}.asymmetric import ec\nk = ec.generate_private_key(ec.SECP256R1())\nz = k.exchange(ec.ECDH(), p)\n",
     [("PY-CRYPTOGRAPHY-EC-001", "ECDH", "key_generation", None), ("PY-CRYPTOGRAPHY-ECDH-001", "ECDH", "key_agreement", None)]),
    ("ec_ambiguous_stays_ec", "t.py", f"from {PYC}.asymmetric import ec\nk = ec.generate_private_key(ec.SECP256R1())\ns = k.sign(d, ec.ECDSA(None))\nz = k.exchange(ec.ECDH(), p)\n",
     [("PY-CRYPTOGRAPHY-EC-001", "EC", "key_generation", None), ("PY-CRYPTOGRAPHY-ECDSA-001", "ECDSA", "signature", None), ("PY-CRYPTOGRAPHY-ECDH-001", "ECDH", "key_agreement", None)]),
    ("ed25519", "t.py", f"from {PYC}.asymmetric.ed25519 import Ed25519PrivateKey\nk = Ed25519PrivateKey.generate()\n", [("PY-CRYPTOGRAPHY-EDDSA-001", "EdDSA", "key_generation", None)]),
    ("nacl", "t.py", "from nacl.signing import SigningKey, VerifyKey\nsk = SigningKey.generate()\nvk = VerifyKey(b)\n",
     [("PY-NACL-EDDSA-001", "EdDSA", "key_generation", None), ("PY-NACL-EDDSA-001", "EdDSA", "verification", None)]),
    ("python_ecdsa_pkg", "t.py", "import ecdsa\nsk = ecdsa.SigningKey.generate(curve=ecdsa.NIST256p)\nvk = ecdsa.VerifyingKey.from_string(b)\n",
     [("PY-ECDSA-ECDSA-001", "ECDSA", "key_generation", None), ("PY-ECDSA-ECDSA-001", "ECDSA", "verification", None)]),
    ("jwt_encode_algs", "t.py", "import jwt\na = jwt.encode(p, k, algorithm='ES256')\nb = jwt.encode(p, k, algorithm='HS256')\nc = jwt.encode(p, k, 'RS256')\n",
     [("PY-PYJWT-001", "ECDSA", "signature", None), ("PY-PYJWT-001", "HMAC", "mac_generation", None), ("PY-PYJWT-001", "RSA", "signature", None)]),
    ("jwt_decode_list", "t.py", "import jwt\nd = jwt.decode(t, k, algorithms=['RS256', 'ES256'])\n",
     [("PY-PYJWT-002", "RSA", "verification", None), ("PY-PYJWT-002", "ECDSA", "verification", None)]),
    ("aes_pycryptodome", "t.py", "from Crypto.Cipher import AES\nc = AES.new(key, AES.MODE_GCM)\n", [("PY-PYCRYPTODOME-AES-001", "AES", "encryption", None)]),
    ("aes_cryptography", "t.py", f"from {PYC}.ciphers.aead import AESGCM\na = AESGCM(key)\nk = AESGCM.generate_key(bit_length=128)\n",
     [("PY-CRYPTOGRAPHY-AES-001", "AES", "encryption", None), ("PY-CRYPTOGRAPHY-AES-002", "AES", "key_generation", 128)]),
    ("aes256_class", "t.py", f"from {PYC}.ciphers import algorithms\na = algorithms.AES256(k)\n", [("PY-CRYPTOGRAPHY-AES-001", "AES", "encryption", 256)]),
    ("hashlib_named", "t.py", "import hashlib\na = hashlib.sha1(b)\nb = hashlib.sha3_256(b)\nc = hashlib.sha256(b)\nd = hashlib.md5(b)\n",
     [("PY-HASHLIB-001", "SHA-1", "hashing", None), ("PY-HASHLIB-001", "SHA-3", "hashing", None), ("PY-HASHLIB-001", "SHA-256", "hashing", None)]),
    ("hashlib_new", "t.py", "import hashlib\nh = hashlib.new('sha1')\nk = hashlib.pbkdf2_hmac('sha256', pw, salt, 1000)\n",
     [("PY-HASHLIB-002", "SHA-1", "hashing", None), ("PY-HASHLIB-002", "SHA-256", "hashing", None)]),
    ("cryptography_hash", "t.py", f"from {PYC} import hashes\nd = hashes.Hash(hashes.SHA1())\n", [("PY-CRYPTOGRAPHY-HASH-001", "SHA-1", "hashing", None)]),
    ("pycryptodome_hash", "t.py", "from Crypto.Hash import SHA256\nh = SHA256.new(b)\n", [("PY-PYCRYPTODOME-HASH-001", "SHA-256", "hashing", None)]),
    ("hmac", "t.py", "import hmac\nm = hmac.new(k, b, 'sha256')\nd = hmac.digest(k, b, 'sha256')\n",
     [("PY-HMAC-001", "HMAC", "mac_generation", None), ("PY-HMAC-001", "HMAC", "mac_generation", None)]),
    ("oqs", "t.py", "import oqs\nk = oqs.KeyEncapsulation('ML-KEM-768')\ns = oqs.Signature('ML-DSA-65')\nh = oqs.Signature('SLH-DSA-SHA2-128s')\n",
     [("PY-OQS-KEM-001", "ML-KEM", "key_generation", None), ("PY-OQS-SIG-001", "ML-DSA", "key_generation", None), ("PY-OQS-SIG-001", "SLH-DSA", "key_generation", None)]),
]

JAVA = [
    ("kpg_rsa", JH + 'KeyPairGenerator g = KeyPairGenerator.getInstance("RSA");\ng.initialize(2048);\n', [("JAVA-JCA-KPG-001", "RSA", "key_generation", 2048)]),
    ("kpg_ec_unresolved", JH + 'KeyPairGenerator g = KeyPairGenerator.getInstance("EC");\n', [("JAVA-JCA-KPG-001", "EC", "key_generation", None)]),
    ("kpg_ec_resolved", JH + 'KeyPairGenerator g = KeyPairGenerator.getInstance("EC");\nSignature s = Signature.getInstance("SHA256withECDSA");\n',
     [("JAVA-JCA-KPG-001", "ECDSA", "key_generation", None), ("JAVA-JCA-SIG-001", "ECDSA", "signature", None)]),
    ("kpg_variants", JH + 'KeyPairGenerator.getInstance("DSA");\nKeyPairGenerator.getInstance("DiffieHellman");\nKeyPairGenerator.getInstance("Ed25519");\nKeyPairGenerator.getInstance("X25519");\n',
     [("JAVA-JCA-KPG-001", "DSA", "key_generation", None), ("JAVA-JCA-KPG-001", "DH", "key_generation", None),
      ("JAVA-JCA-KPG-001", "EdDSA", "key_generation", None), ("JAVA-JCA-KPG-001", "ECDH", "key_generation", None)]),
    ("sig_sha1_rsa", JH + 'Signature s = Signature.getInstance("SHA1withRSA");\n', [("JAVA-JCA-SIG-001", "RSA", "signature", None), ("JAVA-JCA-SIG-002", "SHA-1", "hashing", None)]),
    ("sig_verify", JH + 'Signature s = Signature.getInstance("SHA256withRSA");\ns.initVerify(pub);\n', [("JAVA-JCA-SIG-001", "RSA", "verification", None)]),
    ("sig_pss_ed", JH + 'Signature.getInstance("RSASSA-PSS");\nSignature.getInstance("Ed25519");\n', [("JAVA-JCA-SIG-001", "RSA", "signature", None), ("JAVA-JCA-SIG-001", "EdDSA", "signature", None)]),
    ("keyagreement", JH + 'KeyAgreement.getInstance("ECDH");\nKeyAgreement.getInstance("DH");\nKeyAgreement.getInstance("XDH");\n',
     [("JAVA-JCA-KA-001", "ECDH", "key_agreement", None), ("JAVA-JCA-KA-001", "DH", "key_agreement", None), ("JAVA-JCA-KA-001", "ECDH", "key_agreement", None)]),
    ("cipher_rsa_decrypt", JH + 'Cipher c = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");\nc.init(Cipher.DECRYPT_MODE, k);\n', [("JAVA-JCA-CIPHER-001", "RSA", "decryption", None)]),
    ("cipher_aes", JH + 'Cipher.getInstance("AES/GCM/NoPadding");\nCipher.getInstance("AES_256/GCM/NoPadding");\n', [("JAVA-JCA-CIPHER-002", "AES", "encryption", None), ("JAVA-JCA-CIPHER-002", "AES", "encryption", 256)]),
    ("keygen_aes", JH + 'KeyGenerator kg = KeyGenerator.getInstance("AES");\nkg.init(256);\n', [("JAVA-JCA-KEYGEN-001", "AES", "key_generation", 256)]),
    ("messagedigest", JH + 'MessageDigest.getInstance("SHA-1");\nMessageDigest.getInstance("SHA-256");\nMessageDigest.getInstance("SHA3-512");\nMessageDigest.getInstance("MD5");\n',
     [("JAVA-JCA-MD-001", "SHA-1", "hashing", None), ("JAVA-JCA-MD-001", "SHA-256", "hashing", None), ("JAVA-JCA-MD-001", "SHA-3", "hashing", None)]),
    ("mac", JH + 'Mac m = Mac.getInstance("HmacSHA256");\n', [("JAVA-JCA-MAC-001", "HMAC", "mac_generation", None)]),
    ("bouncycastle", "import org.bouncycastle.crypto.signers.ECDSASigner;\nvar a = new ECDSASigner();\nvar b = new RSAKeyPairGenerator();\nvar c = new SHA256Digest();\nvar d = new HMac(new SHA256Digest());\n",
     [("JAVA-BC-001", "ECDSA", "signature", None), ("JAVA-BC-001", "RSA", "key_generation", None), ("JAVA-BC-001", "SHA-256", "hashing", None),
      ("JAVA-BC-001", "HMAC", "mac_generation", None), ("JAVA-BC-001", "SHA-256", "hashing", None)]),
    ("pqc", JH + 'KEM k = KEM.getInstance("ML-KEM-768");\nKeyPairGenerator.getInstance("ML-DSA");\nKeyPairGenerator.getInstance("ML-KEM");\nvar s = MLDSAParameterSpec.ml_dsa_65;\nvar t = MLKEMParameterSpec.ml_kem_768;\n',
     [("JAVA-PQC-002", "ML-KEM", "encapsulation", None), ("JAVA-JCA-KPG-001", "ML-DSA", "key_generation", None), ("JAVA-JCA-KPG-001", "ML-KEM", "key_generation", None),
      ("JAVA-PQC-001", "ML-DSA", "key_generation", None), ("JAVA-PQC-001", "ML-KEM", "key_generation", None)]),
]

JSH = "const crypto = require('crypto');\n"
JS = [
    ("keypair_rsa", "t.js", JSH + "crypto.generateKeyPairSync('rsa', { modulusLength: 2048 });\n", [("JS-NODE-CRYPTO-KEYPAIR-001", "RSA", "key_generation", 2048)]),
    ("keypair_variants", "t.js", JSH + "crypto.generateKeyPairSync('ed25519');\ncrypto.generateKeyPairSync('x25519');\ncrypto.generateKeyPair('dsa', {}, cb);\n",
     [("JS-NODE-CRYPTO-KEYPAIR-001", "EdDSA", "key_generation", None), ("JS-NODE-CRYPTO-KEYPAIR-001", "ECDH", "key_generation", None), ("JS-NODE-CRYPTO-KEYPAIR-001", "DSA", "key_generation", None)]),
    ("keypair_ec", "t.js", JSH + "crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' });\n", [("JS-NODE-CRYPTO-KEYPAIR-001", "EC", "key_generation", None)]),
    ("sign_ambiguous", "t.js", JSH + "const s = crypto.createSign('sha256');\nconst v = crypto.createVerify('sha256');\n",
     [("JS-NODE-CRYPTO-SIGN-001", "RSA/ECDSA", "signature", None), ("JS-NODE-CRYPTO-SIGN-001", "RSA/ECDSA", "verification", None)]),
    ("sign_rsa_explicit", "t.js", JSH + "const s = crypto.createSign('RSA-SHA256');\n", [("JS-NODE-CRYPTO-SIGN-002", "RSA", "signature", None)]),
    ("ecdh", "t.js", JSH + "const e = crypto.createECDH('prime256v1');\n", [("JS-NODE-CRYPTO-ECDH-001", "ECDH", "key_agreement", None)]),
    ("dh", "t.js", JSH + "crypto.createDiffieHellman(2048);\ncrypto.getDiffieHellman('modp14');\n", [("JS-NODE-CRYPTO-DH-001", "DH", "key_agreement", None)] * 2),
    ("dh_keyobjects", "t.js", JSH + "const s = crypto.diffieHellman({ privateKey: a, publicKey: b });\n", [("JS-NODE-CRYPTO-DH-002", "DH/ECDH", "key_agreement", None)]),
    ("rsa_enc", "t.js", JSH + "crypto.publicEncrypt(key, buf);\ncrypto.privateDecrypt(key, buf);\n",
     [("JS-NODE-CRYPTO-RSA-ENC-001", "RSA", "encryption", None), ("JS-NODE-CRYPTO-RSA-ENC-001", "RSA", "decryption", None)]),
    ("hash", "t.js", JSH + "crypto.createHash('sha1');\ncrypto.createHash(\"sha256\");\ncrypto.createHash('sha3-256');\ncrypto.createHash('md5');\n",
     [("JS-NODE-CRYPTO-HASH-001", "SHA-1", "hashing", None), ("JS-NODE-CRYPTO-HASH-001", "SHA-256", "hashing", None), ("JS-NODE-CRYPTO-HASH-001", "SHA-3", "hashing", None)]),
    ("hmac", "t.js", JSH + "crypto.createHmac('sha256', key);\n", [("JS-NODE-CRYPTO-HMAC-001", "HMAC", "mac_generation", None)]),
    ("aes", "t.js", JSH + "crypto.createCipheriv('aes-256-gcm', k, iv);\ncrypto.createDecipheriv('aes-128-cbc', k, iv);\n",
     [("JS-NODE-CRYPTO-AES-001", "AES", "encryption", 256), ("JS-NODE-CRYPTO-AES-001", "AES", "decryption", 128)]),
    ("ts_named_import", "t.ts", "import { createHash } from \"node:crypto\";\nconst h: string = createHash(\"sha256\").update(x).digest('hex');\n", [("JS-NODE-CRYPTO-HASH-001", "SHA-256", "hashing", None)]),
    ("webcrypto", "t.js", "await crypto.subtle.generateKey({ name: \"ECDSA\", namedCurve: \"P-256\" }, true, [\"sign\"]);\nawait crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, []);\n",
     [("JS-WEBCRYPTO-001", "ECDSA", "signature", None), ("JS-WEBCRYPTO-001", "AES", "encryption", None)]),
    ("forge", "t.js", "const forge = require('node-forge');\nforge.pki.rsa.generateKeyPair({bits: 2048});\nforge.md.sha1.create();\nforge.hmac.create();\nforge.pki.ed25519.generateKeyPair();\nforge.cipher.createCipher('AES-GCM', key);\n",
     [("JS-FORGE-RSA-001", "RSA", "key_generation", 2048), ("JS-FORGE-HASH-001", "SHA-1", "hashing", None), ("JS-FORGE-HMAC-001", "HMAC", "mac_generation", None),
      ("JS-FORGE-ED25519-001", "EdDSA", "key_generation", None), ("JS-FORGE-AES-001", "AES", "encryption", None)]),
    ("jose", "t.ts", "import { SignJWT, jwtVerify } from 'jose';\nnew SignJWT(p).setProtectedHeader({ alg: 'ES256' });\nawait jwtVerify(t, k, { algorithms: ['RS256'] });\n",
     [("JS-JOSE-001", "ECDSA", "signature", None), ("JS-JOSE-002", "RSA", "verification", None)]),
    ("cryptojs", "t.js", "import CryptoJS from 'crypto-js';\nCryptoJS.AES.encrypt(m, k);\nCryptoJS.SHA1(m);\nCryptoJS.HmacSHA256(m, k);\n",
     [("JS-CRYPTOJS-001", "AES", "encryption", None), ("JS-CRYPTOJS-001", "SHA-1", "hashing", None), ("JS-CRYPTOJS-001", "HMAC", "mac_generation", None)]),
    ("tweetnacl", "t.js", "const nacl = require('tweetnacl');\nnacl.sign.keyPair();\nnacl.sign(msg, sk);\nnacl.sign.detached(m, sk);\nnacl.sign.open(sm, pk);\n",
     [("JS-TWEETNACL-001", "EdDSA", "key_generation", None), ("JS-TWEETNACL-001", "EdDSA", "signature", None), ("JS-TWEETNACL-001", "EdDSA", "signature", None), ("JS-TWEETNACL-001", "EdDSA", "verification", None)]),
]
